# Generated by Django 5.0.6 on 2024-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(default='', max_length=150)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.CharField(default='', max_length=150)),
                ('valor_total', models.FloatField(default=0.0)),
            ],
        ),
    ]
